FROM java:8

RUN in -snf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' > /etc/timezone

#将本地文件夹挂载到当前容器
#VOLUME /tep

ADD springcloud-0.0.1-SNAPSHOT.jar app.jar
#RUN ["/bin/bash","-c","touch /app.jar"]

#指定JAVA环境变量
#ENV JAVA_HOME /jdk/jre
#ENV PATH $PATH;$JAVA_HOME/bin
#ENV CLASSPATH .:$JAVA_HOME/lib/rt.jar;$JAVA_HOME/lib/dt.jar;$JAVA_HOME/lib/tools.jar
#开放8000端口
EXPOSE 8000
#配置容器启动后执行的命令
ENTRYPOINT ["java","-jar","/app.jar"]